"""
TokenDNA / Aegis — AWS account connector
Handles the onboarding wizard: generates ExternalId, tests STS AssumeRole,
and runs a quick posture check to validate permissions before saving.
"""
from __future__ import annotations

import logging
import os
import secrets
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional

logger = logging.getLogger(__name__)

# boto3 is an optional dependency — only needed for the Aegis scan module
try:
    import boto3
    from botocore.exceptions import BotoCoreError, ClientError
    _BOTO3_AVAILABLE = True
except ImportError:
    _BOTO3_AVAILABLE = False
    logger.warning("boto3 not installed — AWS connector disabled. pip install boto3")


# ── Data classes ──────────────────────────────────────────────────────────────

@dataclass
class AwsConnectionConfig:
    tenant_id:          str
    account_id:         str          # 12-digit AWS account ID
    scan_role_arn:      str          # arn:aws:iam::<acct>:role/AegisScanRole
    external_id:        str          # secret token, generated by us
    remediation_role_arn: Optional[str] = None
    regions:            list[str]    = field(default_factory=lambda: ["us-east-1"])
    connected_at:       Optional[datetime] = None
    last_scan:          Optional[datetime] = None


@dataclass
class ConnectionTestResult:
    success:     bool
    account_id:  str
    iam_ok:      bool  = False
    ec2_ok:      bool  = False
    s3_ok:       bool  = False
    guardduty_ok: bool = False
    errors:      list[str] = field(default_factory=list)
    warnings:    list[str] = field(default_factory=list)


# ── Onboarding helpers ────────────────────────────────────────────────────────

def generate_external_id() -> str:
    """
    Generate a cryptographically random ExternalId for the CloudFormation template.
    This prevents confused-deputy attacks when the customer deploys the role.
    """
    return "aegis-" + secrets.token_urlsafe(32)


def get_cloudformation_url(external_id: str, aegis_account_id: str) -> str:
    """
    Return a one-click CloudFormation launch URL. The customer clicks this
    link and the wizard pre-fills ExternalId and AegisPlatformAccountId.
    """
    import urllib.parse
    template_url = (
        "https://raw.githubusercontent.com/Bobcatsfan33/Aegis-/main/"
        "onboarding/cloudformation_aegis_role.yml"
    )
    params = {
        "templateURL": template_url,
        "stackName": "AegisSecurityRoles",
        "param_ExternalId": external_id,
        "param_AegisPlatformAccountId": aegis_account_id,
    }
    qs = urllib.parse.urlencode(params)
    return f"https://console.aws.amazon.com/cloudformation/home#/stacks/create/review?{qs}"


# ── STS session helper ────────────────────────────────────────────────────────

def _assume_role(role_arn: str, external_id: str, session_name: str = "AegisScan"):
    """Assume a cross-account role and return a boto3 Session."""
    if not _BOTO3_AVAILABLE:
        raise RuntimeError("boto3 is not installed")

    sts = boto3.client("sts")
    resp = sts.assume_role(
        RoleArn=role_arn,
        RoleSessionName=session_name,
        ExternalId=external_id,
        DurationSeconds=3600,
    )
    creds = resp["Credentials"]
    return boto3.Session(
        aws_access_key_id=creds["AccessKeyId"],
        aws_secret_access_key=creds["SecretAccessKey"],
        aws_session_token=creds["SessionToken"],
    )


# ── Connection test ───────────────────────────────────────────────────────────

def test_connection(config: AwsConnectionConfig) -> ConnectionTestResult:
    """
    Called at the end of the onboarding wizard. Assumes the role and exercises
    each permission category. Returns a report of what worked and what didn't.
    """
    result = ConnectionTestResult(success=False, account_id=config.account_id)

    if not _BOTO3_AVAILABLE:
        result.errors.append("boto3 not installed on server — install it to enable AWS scanning")
        return result

    try:
        session = _assume_role(config.scan_role_arn, config.external_id)
    except ClientError as e:
        result.errors.append(f"STS AssumeRole failed: {e.response['Error']['Message']}")
        return result
    except Exception as e:
        result.errors.append(f"STS error: {e}")
        return result

    # Verify we landed in the right account
    caller = session.client("sts").get_caller_identity()
    if caller["Account"] != config.account_id:
        result.errors.append(
            f"Account mismatch: expected {config.account_id}, got {caller['Account']}"
        )
        return result

    # ── IAM ───────────────────────────────────────────────────────────────────
    try:
        iam = session.client("iam")
        iam.get_account_summary()
        result.iam_ok = True
    except Exception as e:
        result.warnings.append(f"IAM check failed: {e}")

    # ── EC2 ───────────────────────────────────────────────────────────────────
    try:
        ec2 = session.client("ec2", region_name=config.regions[0])
        ec2.describe_security_groups(MaxResults=5)
        result.ec2_ok = True
    except Exception as e:
        result.warnings.append(f"EC2 check failed: {e}")

    # ── S3 ────────────────────────────────────────────────────────────────────
    try:
        s3 = session.client("s3")
        s3.list_buckets()
        result.s3_ok = True
    except Exception as e:
        result.warnings.append(f"S3 check failed: {e}")

    # ── GuardDuty ─────────────────────────────────────────────────────────────
    try:
        gd = session.client("guardduty", region_name=config.regions[0])
        gd.list_detectors()
        result.guardduty_ok = True
    except Exception as e:
        result.warnings.append(f"GuardDuty check failed (non-critical): {e}")

    result.success = result.iam_ok and result.ec2_ok
    return result


# ── Quick posture scan ────────────────────────────────────────────────────────

def quick_posture_scan(config: AwsConnectionConfig, region: str | None = None) -> dict[str, Any]:
    """
    Run a fast (< 30s) posture check across the most critical surfaces.
    Returns a findings dict suitable for the Aegis scan result schema.
    """
    if not _BOTO3_AVAILABLE:
        return {"error": "boto3 not installed"}

    region = region or (config.regions[0] if config.regions else "us-east-1")
    session = _assume_role(config.scan_role_arn, config.external_id)
    findings = []

    # ── IAM: root account MFA ─────────────────────────────────────────────────
    try:
        iam = session.client("iam")
        summary = iam.get_account_summary()["SummaryMap"]
        if summary.get("AccountMFAEnabled", 0) == 0:
            findings.append({
                "severity": "CRITICAL",
                "category": "IAM",
                "title": "Root account has no MFA",
                "resource": f"arn:aws:iam::{config.account_id}:root",
                "remediation": "Enable MFA on the root account immediately.",
            })
    except Exception as e:
        logger.warning("IAM root MFA check failed: %s", e)

    # ── IAM: users with no MFA ────────────────────────────────────────────────
    try:
        paginator = iam.get_paginator("get_account_authorization_details")
        for page in paginator.paginate(Filter=["User"]):
            for user in page["UserDetailList"]:
                if not user.get("MFADevices"):
                    findings.append({
                        "severity": "HIGH",
                        "category": "IAM",
                        "title": f"IAM user '{user['UserName']}' has no MFA",
                        "resource": user["Arn"],
                        "remediation": "Enforce MFA policy or use SSO.",
                    })
    except Exception as e:
        logger.warning("IAM user MFA check failed: %s", e)

    # ── S3: public buckets ────────────────────────────────────────────────────
    try:
        s3 = session.client("s3")
        buckets = s3.list_buckets().get("Buckets", [])
        for bucket in buckets:
            name = bucket["Name"]
            try:
                acl = s3.get_bucket_acl(Bucket=name)
                for grant in acl.get("Grants", []):
                    grantee = grant.get("Grantee", {})
                    if grantee.get("URI") == "http://acs.amazonaws.com/groups/global/AllUsers":
                        findings.append({
                            "severity": "CRITICAL",
                            "category": "S3",
                            "title": f"Bucket '{name}' is publicly readable",
                            "resource": f"arn:aws:s3:::{name}",
                            "remediation": "Remove public ACL and enable Block Public Access.",
                        })
            except ClientError:
                pass
    except Exception as e:
        logger.warning("S3 public bucket check failed: %s", e)

    # ── EC2: security groups with 0.0.0.0/0 on sensitive ports ───────────────
    DANGEROUS_PORTS = {22: "SSH", 3389: "RDP", 5900: "VNC", 6379: "Redis", 27017: "MongoDB"}
    try:
        ec2 = session.client("ec2", region_name=region)
        sgs = ec2.describe_security_groups()["SecurityGroups"]
        for sg in sgs:
            for rule in sg.get("IpPermissions", []):
                from_port = rule.get("FromPort", 0)
                to_port   = rule.get("ToPort", 65535)
                for cidr in rule.get("IpRanges", []):
                    if cidr.get("CidrIp") == "0.0.0.0/0":
                        for port, name in DANGEROUS_PORTS.items():
                            if from_port <= port <= to_port:
                                findings.append({
                                    "severity": "HIGH",
                                    "category": "Network",
                                    "title": f"Security group '{sg['GroupName']}' exposes {name} port {port} to 0.0.0.0/0",
                                    "resource": sg["GroupId"],
                                    "remediation": f"Restrict port {port} to known IP ranges.",
                                })
    except Exception as e:
        logger.warning("EC2 SG check failed: %s", e)

    return {
        "account_id": config.account_id,
        "region": region,
        "scan_time": datetime.utcnow().isoformat(),
        "total_findings": len(findings),
        "critical": sum(1 for f in findings if f["severity"] == "CRITICAL"),
        "high":     sum(1 for f in findings if f["severity"] == "HIGH"),
        "findings": findings,
    }
